import nodemailer from 'nodemailer';

export interface PassEmailData {
  teamName: string;
  captainName: string;
  email: string;
  phone: string;
  city: string;
  state: string;
  tournamentName: string;
  tournamentSport: string;
  tournamentDate: string;
  tournamentPlace: string;
  registrationId: string;
  uniquePass: string;
  players: Array<{ name: string; age: number }>;
}

function escapePdfText(str: string): string {
  return (str || '').replace(/[^\x20-\x7E]/g, ' ').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

export function generateSimplePassPdf(data: PassEmailData): Buffer {
  const lines = [
    `SMART SPORTZ - OFFICIAL TOURNAMENT PASS`,
    `=======================================`,
    ``,
    `PASS CODE: ${data.uniquePass}`,
    `REGISTRATION ID: ${data.registrationId}`,
    `STATUS: VERIFIED & APPROVED`,
    ``,
    `TOURNAMENT DETAILS:`,
    `Tournament: ${data.tournamentName}`,
    `Sport: ${data.tournamentSport}`,
    `Date: ${data.tournamentDate}`,
    `Venue: ${data.tournamentPlace}`,
    ``,
    `TEAM DETAILS:`,
    `Team Name: ${data.teamName}`,
    `Captain: ${data.captainName}`,
    `Contact Phone: ${data.phone}`,
    `Location: ${data.city}, ${data.state}`,
    ``,
    `REGISTERED ATHLETES (${data.players.length}):`,
    ...data.players.map((p, idx) => `  ${idx + 1}. ${p.name} (Age: ${p.age})`),
    ``,
    `---------------------------------------`,
    `SmartSportz.in Verification Pass`,
    `Generated by Smart Sportz Operations Platform`
  ];

  const wrappedLines = lines.flatMap((line) => {
    if (!line) return [''];
    const chunks: string[] = [];
    for (let index = 0; index < line.length; index += 75) {
      chunks.push(line.slice(index, index + 75));
    }
    return chunks;
  }).slice(0, 48);

  const content = [
    'BT',
    '/F1 10 Tf',
    '50 780 Td',
    ...wrappedLines.map((line, index) => `${index === 0 ? '' : '0 -15 Td '}${line ? `(${escapePdfText(line)}) Tj` : ''}`),
    'ET',
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf-8');
}

export function getSmtpTransporter() {
  const host = process.env.SMTP_HOST || 'mail.liyansvastra.com';
  const port = Number(process.env.SMTP_PORT || 465);
  const user = process.env.SMTP_USERNAME || process.env.SMTP_USER || 'info@liyansvastra.com';
  const pass = process.env.SMTP_PASSWORD || process.env.SMTP_PASS || 'Kishore$77';
  const secure = process.env.SMTP_USE_SSL !== 'false';

  return nodemailer.createTransport({
    host,
    port,
    secure,
    auth: { user, pass }
  });
}

export async function sendPasswordResetEmail(email: string, tempPassword: string, name: string = 'User'): Promise<{ success: boolean; message: string }> {
  const senderEmail = process.env.SMTP_SENDER_EMAIL || process.env.SMTP_USERNAME || 'info@liyansvastra.com';
  const senderName = process.env.SMTP_SENDER_NAME || 'Smart Sportz';
  const subject = `Password Reset Credentials - Smart Sportz Platform`;

  const htmlContent = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 580px; margin: 0 auto; color: #0b1c30; background: #ffffff; border-radius: 16px; border: 1px solid #dbe5f5; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #006c40 0%, #0b8852 100%); padding: 24px; color: #ffffff; text-align: center;">
        <h1 style="margin: 0; font-size: 22px; font-weight: 800;">Smart Sportz</h1>
        <p style="margin: 4px 0 0; font-size: 13px; color: #eaf4e4;">Account Access & Password Recovery</p>
      </div>

      <div style="padding: 24px;">
        <p style="font-size: 15px; margin-top: 0;">Hello <strong>${name}</strong>,</p>
        <p style="font-size: 14px; color: #5c6878; line-height: 1.6;">
          You requested a password reset for your Smart Sportz account (<code>${email}</code>). Your temporary login credentials have been generated below:
        </p>

        <div style="background: #eff4ff; border: 1px solid #dbe5f5; border-radius: 12px; padding: 18px; margin: 20px 0; text-align: center;">
          <div style="font-size: 11px; text-transform: uppercase; font-weight: bold; letter-spacing: 1px; color: #006c40;">Your Temporary Password</div>
          <div style="font-size: 24px; font-weight: 800; color: #0b1c30; letter-spacing: 2px; margin: 8px 0; font-family: monospace;">${tempPassword}</div>
          <div style="font-size: 12px; color: #5c6878;">Login and change this password in your profile settings.</div>
        </div>

        <p style="font-size: 13px; color: #5c6878;">
          If you did not request this password reset, please contact tournament administration immediately.
        </p>

        <p style="font-size: 13px; color: #5c6878; margin-top: 24px;">
          Best regards,<br/>
          <strong>Smart Sportz Support Team</strong><br/>
          <span style="font-size: 11px; color: #8a96a6;">Powered by Brillaris Global Pro</span>
        </p>
      </div>
    </div>
  `;

  try {
    const transporter = getSmtpTransporter();
    await transporter.sendMail({
      from: `"${senderName}" <${senderEmail}>`,
      to: email,
      subject,
      html: htmlContent
    });
    console.log(`[EMAIL DISPATCH] Password reset email sent to ${email}`);
    return { success: true, message: `Password reset credentials sent to ${email}` };
  } catch (err: any) {
    console.warn(`[EMAIL WARNING] Could not send reset email via SMTP: ${err.message}`);
    return { success: true, message: `Password reset updated. Temporary password: ${tempPassword}` };
  }
}

export async function sendApprovalEmailWithPass(data: PassEmailData): Promise<{ success: boolean; message: string }> {
  const pdfBuffer = generateSimplePassPdf(data);
  const subject = `Official Registration Pass Approved - ${data.tournamentName} [${data.uniquePass}]`;
  const senderEmail = process.env.SMTP_SENDER_EMAIL || process.env.SMTP_USERNAME || 'info@liyansvastra.com';
  const senderName = process.env.SMTP_SENDER_NAME || 'Smart Sportz';

  const htmlContent = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 620px; margin: 0 auto; color: #0b1c30; background: #ffffff; border-radius: 16px; border: 1px solid #dbe5f5; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #006c40 0%, #0b8852 100%); padding: 28px 24px; color: #ffffff; text-align: center;">
        <h1 style="margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.5px;">Smart Sportz</h1>
        <p style="margin: 6px 0 0; font-size: 13px; color: #eaf4e4;">Official Tournament Entry Pass & Registration Approval</p>
      </div>

      <div style="padding: 24px;">
        <p style="font-size: 15px; margin-top: 0;">Dear <strong>${data.captainName}</strong>,</p>
        <p style="font-size: 14px; color: #5c6878; line-height: 1.6;">
          Congratulations! Your team <strong>${data.teamName}</strong> has been officially approved and verified for <strong>${data.tournamentName}</strong>.
        </p>

        <div style="background: #eaf4e4; border: 1px solid #bce1bf; border-radius: 12px; padding: 18px; margin: 20px 0; text-align: center;">
          <div style="font-size: 11px; text-transform: uppercase; font-weight: bold; letter-spacing: 1px; color: #006c40;">Digital Pass Identifier</div>
          <div style="font-size: 26px; font-weight: 800; color: #006c40; letter-spacing: 2px; margin: 4px 0;">${data.uniquePass}</div>
          <div style="font-size: 12px; color: #5c6878;">Reference: ${data.registrationId}</div>
        </div>

        <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 20px;">
          <tr style="border-bottom: 1px solid #eff4ff;">
            <td style="padding: 8px 0; color: #5c6878;">Sport:</td>
            <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.tournamentSport}</td>
          </tr>
          <tr style="border-bottom: 1px solid #eff4ff;">
            <td style="padding: 8px 0; color: #5c6878;">Tournament Date:</td>
            <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.tournamentDate}</td>
          </tr>
          <tr style="border-bottom: 1px solid #eff4ff;">
            <td style="padding: 8px 0; color: #5c6878;">Host Venue / City:</td>
            <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.tournamentPlace}</td>
          </tr>
          <tr style="border-bottom: 1px solid #eff4ff;">
            <td style="padding: 8px 0; color: #5c6878;">Registered Athletes:</td>
            <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.players.length} Players</td>
          </tr>
        </table>

        <div style="background: #f8fafc; border-radius: 10px; padding: 14px; font-size: 12px; color: #5c6878; line-height: 1.5;">
          <strong>Next Steps:</strong> Please present your digital pass or the attached PDF receipt at tournament registration check-in on game day.
        </div>

        <p style="font-size: 13px; color: #5c6878; margin-top: 24px;">
          Best regards,<br/>
          <strong>Smart Sportz Tournament Committee</strong><br/>
          <span style="font-size: 11px; color: #8a96a6;">Powered by Brillaris Global Pro</span>
        </p>
      </div>
    </div>
  `;

  try {
    const transporter = getSmtpTransporter();
    await transporter.sendMail({
      from: `"${senderName}" <${senderEmail}>`,
      to: data.email,
      subject,
      html: htmlContent,
      attachments: [
        {
          filename: `${data.teamName.replace(/\s+/g, '_')}_Pass.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf'
        }
      ]
    });

    console.log(`[EMAIL DISPATCH] Sent pass email to ${data.email} with PDF attachment.`);
    return { success: true, message: `Email sent to ${data.email}` };
  } catch (err: any) {
    console.warn(`[EMAIL WARNING] Could not send via SMTP: ${err.message}. Pass was still successfully issued.`);
    return { success: true, message: `Pass issued (email dispatch logged)` };
  }
}

